### PR TITLE
added my-combinator

### PR DESCRIPTION
**Pull request by ludicast**
don't know whether or not this does it for you, but the my-combinator is what I initially considered instead of letting combinators take strings.  You input into "my" a method name and it returns a function that executes that method on the object.  This lets you have a chain like this

``` coffeescript
class Employee
  promote:
    hireSecretary \
    buyBiggerDesk \
    my("updateProfile")
```

### CODE REVIEW

**Comment by raganwald** [comment]
`my` isn't really a combinator, it's a helper. But one I like!

**Comment by ludicast** [comment]
Okay, so I pulled out of `my` two functions, a `pipe` and a `pipeMy`.  `pipe` behaves like Clojure's threading macro or underscore's compose. `pipeMy` behaves similarly, but first maps `my` to its string input.

This allows you to compose functions like

``` coffeescript
class User
  changePassword:
    provided notLocked \
    pipeMy "validatePassword", "hashPassword", "storePassword", "sendPasswordUpdateEmail"
```

Though `my` might not be a combinator, I'm finding that it helps me avoid situations that crop up as I play with method-combinators:

``` coffeescript
# simultaneously assigning the method name to a variable so it can be referenced in other combinators
class MyClazz
  methodName: methodName = ->  
```

``` coffeescript
# an instance method defined above the class so it can be referenced in combinators
methodName = ->
class MyClass
  aMethod: someCombinator methodName
```

``` coffeescript
# a method at the end of the combinators existing just to delegate to another instance method
class MyClass
  aMethod: someCombinator -> @methodName arguments... 
```

**Comment by raganwald** [comment]
Question: If you have `my` and `splatter` and `pipe`, do you need `pipeMy`? Can't you write `pipeMy = pipe splatter my`?

**Comment by ludicast** [comment]
Doh, great question!  Seems like it does compose more cleanly (I'm still new to this, having only recently finished ristretto): 

``` coffeescript
pipeMy =
    ->
      helpers.pipe ((combinators.splatter helpers.my) arguments)...
```

If it gets composed in userspace it looks like:

``` coffeescript
pipe splatter(my)(["func1", "func2"])...
```

Personally I think that requires too much semantic knowledge as opposed to `pipeMy "func1", "func2"`.

But I'd say the issue is whether or not `pipe` AND `pipeMy` warrant separate functions. If okay with you, it's probably best for me to have `pipe` work with both strings and functions. That was my initial approach before I OCDed it into two separate functions.

Regardless I'll have to rebase or recreate this branch because I'm butchering its history.

**Comment by greghart** [comment]
Sorry ahead of time for necro-ing this thread from so long ago. A very interesting library, and I'm wanting to use it as much as possible! One issue I've had is similar to @ludicast. I don't want to have to define decorators and combinators outside the main class definition. For example, I want to be able to write something like the following, wherein `my` is a true combinator.

``` coffeescript
combinator = MethodCombinators.provided ->
  return true

class Test

  combinator: MethodCombinators.provided ->
    # Calculate if thing is checked
    return isThingChecked()

  # Equivalent
  method: my('combinator') ->
  method: combinator ->
```

I came up with an implementation like:

```
my = (property) ->
  (base) ->
    ->
      method = @[property](base).apply(@, arguments)
```

Is there a better or more semantic way to do this? Thanks for any feedback, just trying to get my head wrapped around this very cool concept.

**Pull request closed without merging**
